#!/usr/bin/env ruby

require 'nokogiri'
require 'open-uri'
require 'json'

stations = %w{radio1 radio2 radio3 radio4 radio4extra 5live 6music}

unless ARGV[0] && ((stations + ['all']).flatten).include?(ARGV[0])
  puts "Usage: nowon [#{stations.join("|")}|all]"
  exit
end

def nowon(station)
  case station
  when '6music', 'radio1'
    station == 'radio1' ? station2 = 'radio_one' : station2 = station
    jsonp = open("https://polling.bbc.co.uk/radio/realtime/bbc_#{station2}.jsonp").read

    # Remove the callback function from the start of the string
    jsonp.gsub!(/realtimeCallback\(/, '')
    # Remove the end of the callback function
    jsonp.gsub!(/\)$/, '')

    json = JSON.load(jsonp)
    track = json['realtime']['title'].strip
    artist = json['realtime']['artist'].strip

    buffer = []

    buffer << "#{artist} - #{track}"
    buffer << iplayer_radio("https://www.bbc.co.uk/#{station}")
    buffer.join("\n")
  when 'radio2', 'radio3', 'radio4', 'radio4extra', '5live'
    iplayer_radio("https://www.bbc.co.uk/#{station}")
  end
end

def iplayer_radio(url)
  doc = Nokogiri::HTML(open(url))

  text = doc.css('.on-air-now .on-air__episode-title').first.text.strip
  synopsis = doc.css('.on-air-now .on-air__episode-synopsis').first.text.strip
  details = doc.css('.on-air-now .on-air__track-now-playing__details').first.text.strip

  "#{text} - #{synopsis}\n#{details}"
end

case ARGV[0]
when 'all'
  buffer = []
  puts "Thinking..."
  puts "-----------"
  stations.each do |station|
    buffer << "*** #{station}"
    buffer << nowon(station)
    buffer << ""
  end
  puts buffer.join("\n")
else 
  puts nowon(ARGV[0])
end
