#!/usr/bin/env ruby

require 'nokogiri'
require 'open-uri'
require 'json'

stations = %w{radio2 radio3 radio4 6music 5live}

unless ARGV[0] && ((stations + ['all']).flatten).include?(ARGV[0])
  puts "Usage: nowon [#{stations.join("|")}|all]"
  exit
end

def nowon(station)
  case station
  when '6music'
    json = JSON.load(open('http://polling.bbc.co.uk/6music/richtracks.json'))
    doc = Nokogiri::HTML(json['body'])

    track = doc.css('.richtrack__trackname')[0].inner_text.strip
    artist = doc.css('.richtrack__artistname')[0].inner_text.strip

    puts "#{artist} - #{track}"
  when 'radio2'
    iplayer_radio('http://www.bbc.co.uk/radio2')
  when 'radio3'
    iplayer_radio('http://www.bbc.co.uk/radio3')
  when 'radio4'
    iplayer_radio('http://www.bbc.co.uk/radio4')
  when '5live'
    iplayer_radio('http://www.bbc.co.uk/5live')
  end
end

def iplayer_radio(url)
  doc = Nokogiri::HTML(open(url))

  text = doc.css('.on-air-now .on-air__episode-title').first.text.strip
  synopsis = doc.css('.on-air-now .on-air__episode-synopsis').first.text.strip
  details = doc.css('.on-air-now .on-air__track-now-playing__details').first.text.strip

  puts "#{text} - #{synopsis}"
  puts details
end

case ARGV[0]
when 'all'
  stations.each do |station|
    puts "*** #{station}"
    nowon(station)
    puts
  end
else 
  nowon(ARGV[0])
end
