#!/usr/bin/env ruby

require 'nokogiri'
require 'open-uri'
require 'json'

stations = %w{radio4 6music}

unless ARGV[0] && ((stations + ['all']).flatten).include?(ARGV[0])
  puts "Usage: nowon [6music|radio4|all]"
  exit
end

def nowon(station)
  case station
  when '6music'
    json = JSON.load(open('http://polling.bbc.co.uk/6music/richtracks.json'))
    doc = Nokogiri::HTML(json['body'])

    track = doc.css('.richtrack__trackname')[0].inner_text.strip
    artist = doc.css('.richtrack__artistname')[0].inner_text.strip

    puts "#{artist} - #{track}"
  when 'radio4'
    doc = Nokogiri::HTML(open('http://www.bbc.co.uk/radio4'))

    text = doc.css('.on-air-now .on-air__episode-title').text.strip
    synopsis = doc.css('.on-air-now .on-air__episode-synopsis').text.strip
    details = doc.css('.on-air-now .on-air__track-now-playing__details').text.strip

    puts "#{text} - #{synopsis}"
    puts details
  end
end

case ARGV[0]
when 'radio4', '6music'
  nowon(ARGV[0])
when 'all'
  stations.each do |station|
    puts "*** #{station}"
    nowon(station)
    puts
  end
end
